name: Robert # Nom du workflow
on: [push] # Evenement
jobs: # Etapes a appliquer
  say-hello: # Nom du job
    runs-on: ubuntu-latest # L'env
    steps:
      - run: echo "Hello, Robert"
  say-good-bye: 
    runs-on: ubuntu-latest
    steps:
      - run: ls -l
      - run: echo "Bye Robert"
    
  
